name: trabalho_01
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter   
  #Permite inserir novo logo no apk gerado para o aplicativo
  flutter_launcher_icons: ^0.9.0
  #Permitindo utilização do firebase para autenticação 
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.3
  firebase_core_platform_interface: ^4.0.0
  # #Permitindo utilização do banco de dados Cloud Firestore
  cloud_firestore: ^1.0.3
  plugin_platform_interface: ^2.0.0
  # #Auxilia o programa a detectar status de conexão do usuário
  connectivity: ^3.0.3
  connectivity_plus: ^1.0.0
  connectivity_plus_linux: ^1.0.0
  dbus: ^0.2.1
  args: ^2.0.0
  # #Permite o redirecionamento da aplicação para outras urls
  url_launcher: ^6.0.3
  # #Permite a utilização do bloc, necessário para a autenticação dos usuários
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  # #Permite conexão com o firebase, utilizado no calendário
  firebase_helpers: ^0.3.1
  # #Permite criação de calendário personalizável
  table_calendar: ^2.3.3
  # #Permite a utilização de icones personalizados, como o do Github, na parte dos desenvolvedores
  flutter_icons: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:  
      - family: CourierPrime-Bold
        fonts:  
          - asset: fonts/CourierPrime-Bold.ttf
          - asset: fonts/CourierPrime-BoldItalic.ttf  
          - asset: fonts/CourierPrime-Italic.ttf  
          - asset: fonts/CourierPrime-Regular.ttf 
      - family: Mistral
        fonts:
          - asset: fonts/mistral.ttf
          - asset: fonts/mistral-regular.ttf
      - family: Mistral
        fonts:
          - asset: fonts/britannic-bold.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  #ios: true
  image_path: "assets/images/icone.jpeg"
